site_name: E-TRAINEE Course
repo_url: https://3dtools.geog.uni-heidelberg.de/etrainee/etrainee
docs_dir: ../course
site_dir: ../site

theme:
  logo: assets/img/logo_etrainee.svg
  favicon: assets/img/logo_etrainee.svg
  name: material
  custom_dir: overrides
  palette:
    primary: teal
    accent: indigo 
  features:
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.footer
use_directory_urls: false
plugins:
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
  - search
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/quiz_evaluation.js
  
nav:
- 'Home': 'index.md'
- 'Module TEST' : 
    - 'lesson' : 'test/subpage.md'
    - 'second subpage': 'test/subpage2.md'
    
